modLoader = "javafml"
loaderVersion = "[36,)"
license = "MIT"
issueTrackerURL="https://github.com/hypherionmc/sdlink/issues" #optional
[[mods]] #mandatory
modId = "sdlink" #mandatory
version = "${file.jarVersion}" #mandatory
displayName = "sdlink" #mandatory
#updateJSONURL="http://myurl.me/" #optional
displayURL="https://github.com/hypherionmc/sdlink" #optional
#logoFile="sdlink-forge.png" #optional
authors="HypherionMC" #optional
description = '''A simple Minecraft to Discord Chat bot with Whitelisting'''

[[dependencies.sdlink]] #optional
modId = "forge" #mandatory
mandatory = true #mandatory
versionRange = "[36,)" #mandatory
ordering = "NONE"
side = "BOTH"

[[dependencies.sdlink]]
modId = "minecraft"
mandatory = true
versionRange = "[1.16.5,1.17)"
ordering = "NONE"
side = "SERVER"
