modLoader = "javafml"
loaderVersion = "[37,)"
license = "MIT"
issueTrackerURL="https://github.com/hypherionmc/sdlink/issues" #optional
[[mods]] #mandatory
modId = "sdlink" #mandatory
version = "1.17.x-${version}" #mandatory
displayName = "sdlink" #mandatory
#updateJSONURL="http://myurl.me/" #optional
displayURL="https://github.com/hypherionmc/sdlink" #optional
logoFile="sdlink_logo.png" #optional
authors="HypherionMC" #optional
description = '''A simple Minecraft to Discord Chat bot with Whitelisting'''

[[dependencies.sdlink]] #optional
modId = "forge" #mandatory
mandatory = true #mandatory
versionRange = "[37,)" #mandatory
ordering = "NONE"
side = "BOTH"

[[dependencies.sdlink]]
modId = "minecraft"
mandatory = true
versionRange="[1.17.1,1.18)"
ordering = "NONE"
side = "SERVER"
